//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLTHONGTINMAYTINHEntities1 : DbContext
    {
        public QLTHONGTINMAYTINHEntities1()
            : base("name=QLTHONGTINMAYTINHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHAKHO> NHAKHOes { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<THONGTINDONHANG> THONGTINDONHANGs { get; set; }
        public virtual DbSet<THONGKEDONHANGDABAN> THONGKEDONHANGDABANs { get; set; }
        public virtual DbSet<THONGKEDONHANGDABAN_1> THONGKEDONHANGDABAN_1 { get; set; }
    
        public virtual ObjectResult<loadINFORDONHANG_Result> loadINFORDONHANG(string mADH)
        {
            var mADHParameter = mADH != null ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<loadINFORDONHANG_Result>("loadINFORDONHANG", mADHParameter);
        }
    
        public virtual ObjectResult<seachName_Result> seachName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seachName_Result>("seachName", nameParameter);
        }
    
        public virtual ObjectResult<SeachNameKhachHang_Result> SeachNameKhachHang(string tenKH)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeachNameKhachHang_Result>("SeachNameKhachHang", tenKHParameter);
        }
    
        public virtual ObjectResult<SeachNameNhaCungCap_Result> SeachNameNhaCungCap(string tenNCC)
        {
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("TenNCC", tenNCC) :
                new ObjectParameter("TenNCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeachNameNhaCungCap_Result>("SeachNameNhaCungCap", tenNCCParameter);
        }
    
        public virtual ObjectResult<SeachNameNhaKHo_Result> SeachNameNhaKHo(string tenNK)
        {
            var tenNKParameter = tenNK != null ?
                new ObjectParameter("TenNK", tenNK) :
                new ObjectParameter("TenNK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeachNameNhaKHo_Result>("SeachNameNhaKHo", tenNKParameter);
        }
    
        public virtual ObjectResult<SeachNameSanPham_Result> SeachNameSanPham(string tenSP)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeachNameSanPham_Result>("SeachNameSanPham", tenSPParameter);
        }
    
        public virtual ObjectResult<ThongKe_Result> ThongKe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKe_Result>("ThongKe");
        }
    
        public virtual ObjectResult<THONGKETHEONGAY_Result> THONGKETHEONGAY(Nullable<System.DateTime> tHONGKE)
        {
            var tHONGKEParameter = tHONGKE.HasValue ?
                new ObjectParameter("THONGKE", tHONGKE) :
                new ObjectParameter("THONGKE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THONGKETHEONGAY_Result>("THONGKETHEONGAY", tHONGKEParameter);
        }
    
        public virtual ObjectResult<THONGKETHEOTHANG_Result> THONGKETHEOTHANG(Nullable<System.DateTime> tHONGKE)
        {
            var tHONGKEParameter = tHONGKE.HasValue ?
                new ObjectParameter("THONGKE", tHONGKE) :
                new ObjectParameter("THONGKE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THONGKETHEOTHANG_Result>("THONGKETHEOTHANG", tHONGKEParameter);
        }
    
        public virtual ObjectResult<Top_5_SP_Result> Top_5_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top_5_SP_Result>("Top_5_SP");
        }
    
        public virtual ObjectResult<Top_5_SP1_Result> Top_5_SP1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top_5_SP1_Result>("Top_5_SP1");
        }
    
        public virtual int UpdateSoLuong(string maSP, Nullable<int> soLuong)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSoLuong", maSPParameter, soLuongParameter);
        }
    }
}
