//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.THONGTINDONHANGs = new HashSet<THONGTINDONHANG>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string THUONGHIEU { get; set; }
        public string THONGTIN { get; set; }
        public string LOAISP { get; set; }
        public int SOLUONG { get; set; }
        public decimal GIANHAP { get; set; }
        public decimal GIABAN { get; set; }
        public System.DateTime TIMENHAP { get; set; }
        public string MANCC { get; set; }
        public string MANK { get; set; }
        public string IMAGES { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHAKHO NHAKHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINDONHANG> THONGTINDONHANGs { get; set; }
    }
}
