//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKEDONHANGDABAN
    {
        public string MADH { get; set; }
        public string TENKH { get; set; }
        public string TENNV { get; set; }
        public System.DateTime TIMEXUAT { get; set; }
        public decimal THANHTIEN { get; set; }
    }
}
